### PR TITLE
Update vulnerabilities.md

### LINKED ISSUE #48: Using delete on an array leaves a gap
```
    function removePrecondition(uint _index) external onlyOwner {
        delete preconditions[_index];
    }
```

### Expected behavior
Removed item from the array

### Actual behavior
Empty gap

### Steps to reproduce the behavior
Try to add and then remove the precondition. The size of an array does not change after removal.

As there is a function that iterates over this array:

```
for (uint idx = 0; idx < preconditions.length; idx++) {
            ....
}
```
 If the array grows very large, the loop could exceed the block gas limit and fail.

### PR DESCRIPTION
**Pull request by pauliax**
fixes #48

### CODE REVIEW

**Review by davy-vr — DISMISSED** [review]
Could you add a new section under the example (and remove the italic markup). We want to keep the example for other users to use as a template for adding new issues.

Also pls reference the issue number using 'fixes'.

Thx!

**Comment by davy-vr** [comment]
Can you update the title of the vulnerability? 
Since you have 2 pull requests, make sure the result contains the 2 vulnerabilities.

Also can you add the "fixes" keyword in your pull request? This is essentials for claiming the reward afterwards :)

**Comment by karelstriegel** [comment]
fixes https://github.com/FundRequest/contracts/issues/48

**Review by karelstriegel — APPROVED** [review]

**Comment by karelstriegel** [comment]
@pauliax , we've found a bug in the flow , so once we've pushed the new fix into master (production) , we will close this issue, which in turn allows you to claim the attached bounty.

So currently blocked by : https://github.com/FundRequest/platform/issues/408

**Pull request merged**
